# Generated by Django 5.0.14 on 2026-06-16 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('siglas', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='#6c757d', max_length=20)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['siglas'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='votos.municipio')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['municipio__nombre', 'numero'],
                'unique_together': {('municipio', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Casilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('B', 'Básica'), ('C', 'Contigua'), ('E', 'Extraordinaria'), ('S', 'Especial')], max_length=1)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casillas', to='votos.seccion')),
            ],
            options={
                'verbose_name': 'Casilla',
                'verbose_name_plural': 'Casillas',
                'ordering': ['seccion__numero', 'tipo', 'numero'],
                'unique_together': {('seccion', 'tipo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoCasilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.PositiveIntegerField(default=0)),
                ('casilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='votos.casilla')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='votos.partido')),
            ],
            options={
                'verbose_name': 'Resultado de casilla',
                'verbose_name_plural': 'Resultados de casilla',
                'ordering': ['casilla', 'partido__siglas'],
                'unique_together': {('casilla', 'partido')},
            },
        ),
    ]
