# Generated by Django 5.0.14 on 2026-06-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_partido_imagen_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['orden_captura', 'siglas'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AddField(
            model_name='partido',
            name='orden_captura',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partido',
            name='tipo',
            field=models.CharField(choices=[('PARTIDO', 'Partido'), ('NULO', 'Voto Nulo'), ('NO_REGISTRADO', 'No Registrado')], default='PARTIDO', max_length=30),
        ),
    ]
