# Generated by Django 5.0.14 on 2026-06-23 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0003_alter_partido_options_partido_orden_captura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casilla',
            name='diferencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casilla',
            name='fecha_captura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casilla',
            name='tiene_diferencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casilla',
            name='total_acta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casilla',
            name='total_calculado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casilla',
            name='usuario_captura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casillas_capturadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
